Mathematisches funktions modul dev
Nex0TV/taschenrechner_it20-1_Team_2 pull request #10
Opened 2023-02-08 07:00 UTC by Nex0TV

2023-02-08 07:29 UTC, benjaminproductions requested changes

2023-02-08 07:29 UTC, benjaminproductions commented on Classes/Mathematik.cs
> +            } while ((x * x).ToString("F6") != zahl.ToString("F6"));
würde die funktion in der while klammer eine zeile darunter setzen um es klarer darzustellen

2023-02-08 07:29 UTC, benjaminproductions commented on TaschenrechnerUnitTests/Mathematik/Bruch.cs
> +        public void input_1_0()
bennung der test funktionen

2023-02-08 07:29 UTC, benjaminproductions commented on TaschenrechnerUnitTests/Mathematik/Potenz.cs
>          public void Input_1p56_4()
bennung der test funktionen

2023-02-08 07:29 UTC, benjaminproductions commented on TaschenrechnerUnitTests/Mathematik/Primzahlen.cs
> +        public void Input_n13_1()
bennung der test funktionen

2023-02-08 07:29 UTC, benjaminproductions commented on TaschenrechnerUnitTests/Mathematik/Wurzel.cs
> +        public void input_1()
bennung der test funktionen

2023-02-08 07:29 UTC, benjaminproductions commented on Classes/Mathematik.cs
> +            double x = 1;
was macht `x`?

2023-02-09 07:30 UTC, Nex0TV commented on Classes/Mathematik.cs
> +            double x = 1;
x ist ein wert im annäherungsverfahren bei der wurzelberechnung

2023-02-09 07:34 UTC, merged