Geometrie dev
Nex0TV/taschenrechner_it20-1_Team_2 pull request #11
Opened 2023-02-08 07:01 UTC by Nex0TV

2023-02-08 07:17 UTC, benjaminproductions requested changes
würde die test klassen zu einer datei migrieren und eine gute benennung geben.
sonst sieht die logic gut aus.

2023-02-08 07:17 UTC, benjaminproductions commented on Classes/Geometrie.cs
> +        private const float Pi = 3.141592653f;
wrong case
should be only `pi`

2023-02-08 07:17 UTC, benjaminproductions commented on Classes/Geometrie.cs
> +            return seitea + seiteb + seitec;
seiteA, seiteB, seiteC

2023-02-08 07:17 UTC, benjaminproductions commented on TaschenrechnerUnitTests/Geometrie/DreieckFlaeche.cs
> +        public void Setup()
wird setup hier benötigt?

2023-02-08 07:17 UTC, benjaminproductions commented on TaschenrechnerUnitTests/Geometrie/DreieckFlaeche.cs
> +        public void Input_0()
bessere funktions bennenung

2023-02-08 07:37 UTC, Nex0TV commented on Classes/Geometrie.cs
> +        private const float Pi = 3.141592653f;
soooo nicht!

2023-02-08 07:44 UTC, Nex0TV commented on TaschenrechnerUnitTests/Geometrie/DreieckFlaeche.cs
> +        public void Input_0()
musst mal lunschen

2023-02-08 10:58 UTC, benjaminproductions commented on TaschenrechnerUnitTests/Geometrie/DreieckFlaeche.cs
> +        public void Input_0()
![2022-11-08_09-25](https://user-images.githubusercontent.com/84847659/217510925-ef804d3a-1457-423e-86c9-865c990b360c.png)

2023-02-09 06:30 UTC, benjaminproductions approved these changes

2023-02-09 06:52 UTC, merged